name: "Barcode"
description: "Reads data from barcode scanner to create a shopping list"
version: "0.0.19"
slug: "barcode"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  keyboard_device: null
schema:
  keyboard_device: device
full_access: true
homeassistant_api: true
ports:
  8888/tcp: 8888